#!/bin/bash

echo "Adding user and group"
if ! getent passwd aws > /dev/null; then
    adduser --system --no-create-home --group aws --shell /sbin/nologin --gecos "aws"
fi
if ! getent group aws > /dev/null; then
    addgroup --system aws
fi
if ! id -Gn aws | grep -qw aws; then
    adduser aws aws
fi

echo "Checking user and group"
if [ "`id -u aws`" -eq 0 ]; then
    echo "The aws system user must not have uid 0 (root). Please fix this and reinstall this package." >&2
    exit 1
fi
if [ "`id -g aws`" -eq 0 ]; then
    echo "The aws system user must not have root as primary group. Please fix this and reinstall this package." >&2
    exit 1
fi

echo "Sharing credentials"
mkdir -p /rotatingcreds
chown aws:aws /rotatingcreds
chmod 750 /rotatingcreds

echo "Setting permissions"
chown -R root:aws /etc/amazon/ssm

mkdir -p /var/lib/amazon
chown root:aws /var/lib/amazon
chmod 750 /var/lib/amazon

mkdir -p /var/log/amazon/ssm
chown -R aws:aws /var/log/amazon/ssm
chmod 755 /var/log/amazon/ssm

mkdir -p /var/lib/amazon/ssm/Vault/Store
chown -R aws:aws /var/lib/amazon/ssm
chmod 700 /var/lib/amazon/ssm/Vault
chmod 700 /var/lib/amazon/ssm/Vault/Store

echo "Starting agent"
if [ $(cat /proc/1/comm) = init ]
then
    start amazon-ssm-agent || true
elif [ $(cat /proc/1/comm) = systemd ]
then
    systemctl enable amazon-ssm-agent
    systemctl start amazon-ssm-agent
    systemctl daemon-reload
fi
